config/routes.rb
Rails.application.routes.draw do
  root 'chapters#index'
  resources :chapters do
    resources :sections do
      resources :lessons
    end
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :sections
  validates :name, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  default_scope { order('number ASC') }
  belongs_to :section
  validates :name, :presence => true
  validates :text, :presence => true
  validates :number, :presence => true

  def next
    findThis = self.number + 1
    result = Lesson.where(number: findThis).first
    if !result
      return self
    else
      return result
    end
  end

  def prev
  findThis = self.number - 1
  result = Lesson.where(number: findThis).first
  if !result
    return self
  else
    return result
  end
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter
  has_many :lessons
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      flash[:notice] = "Chapter Added"
      redirect_to chapters_path
    else
      render :new
    end
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  private
  def chapter_params
    params.require(:chapter).permit(:name)
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.find(params[:section_id])
    @lesson = Lesson.new
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.find(params[:section_id])
    # @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      flash[:notice] = "Lesson Added"
      redirect_to chapters_path
    else
      render :new
    end
  end

  def show
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  private
  def lesson_params
    params.require(:lesson).permit(:name, :text, :number)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @chapter = Chapter.find(params[:chapter_id])
    @sections = Section.all
  end

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.new
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.new(section_params)
    if @section.save
      flash[:notice] = "Section Added"
      redirect_to chapters_path
    else
      render :new
    end
  end

  def show
    @section = Section.find(params[:id])
  end

  private
  def section_params
    params.require(:section).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/_form.html.erb
<%= form_for [@chapter] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/chapters/index.html.erb
<% content_for(:title, 'Table of Contents') %>

<div class="row">
    <% @chapters.each do |c| %>

    <div class="col-md-4 well chapter" style="min-height: 200px;">

      <h2 class="chapter-header"><%= c.name %></h2>
      <% c.sections.each do |s| %>
        <h4 class="section-header"> <%= s.name %> </h4>

        <ul>
        <% s.lessons.each do |l| %>
            <li><%= link_to l.name, chapter_section_lesson_path(c, s, l) %></li>
        <% end %>
        </ul>
        <%= link_to 'Add Lesson', new_chapter_section_lesson_path(c, s) %>
      <% end %>
      <%= link_to 'Add Section', new_chapter_section_path(c) %>

    </div>
    <% end %>
</div>



<br><br>
<%= link_to "New Chapter", new_chapter_path %>

app/views/chapters/new.html.erb
<% content_for(:title, 'Add New Chapter') %>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EpicodusClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="col-md-8 col-md-offset-2 well">
    <h1><%= yield(:title) %></h1>
  </div>
  <div class="container-fluid">
    <div class="col-md-4 col-md-offset-4">
      <span style="color: red;"><%= flash[:alert] %></span>
      <span style="color: blue;"><%= flash[:notice] %></span>
    </div>
    <div class="row">
      <div class="col-md-12">
          <%= yield %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
          <%= link_to "Table of Contents", chapters_path %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for [@chapter, @section, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <p><%= f.submit %></p>
<% end %>

app/views/lessons/new.html.erb
<% content_for(:title, 'Add New Lesson') %>

<%= render 'layouts/errors', :object => @lesson %>

<%= render 'form' %>

app/views/lessons/show.html.erb
<%= @lesson.name %>
<br>
<%= @lesson.text %>
<br>
<%= @lesson.number %>

<%= link_to "Next", chapter_section_lesson_path(@chapter, @section, @lesson.next) %>
<%= link_to "Previous", chapter_section_lesson_path(@chapter, @section, @lesson.prev) %>

app/views/sections/_form.html.erb
<%= form_for [@section] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/sections/new.html.erb
<% content_for(:title, 'Add New Section') %>

<%= render 'form' %>